# Generated by Django 4.2.1 on 2023-05-22 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.attraction')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.place')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'planing the travel'), (1, 'ready to go'), (2, 'I am back')], default=0)),
                ('place_attraction', models.ManyToManyField(through='trip.Days', to='trip.placeattraction')),
            ],
        ),
        migrations.CreateModel(
            name='TravelNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'before the travel'), (1, 'during the travel'), (2, 'after the travel')], default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.travel')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='attraction',
            field=models.ManyToManyField(through='trip.PlaceAttraction', to='trip.attraction'),
        ),
        migrations.AddField(
            model_name='days',
            name='place_attraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.placeattraction'),
        ),
        migrations.AddField(
            model_name='days',
            name='travel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.travel'),
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.attraction')),
            ],
        ),
    ]
