# Generated by Django 4.2.1 on 2023-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_travel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Planowanie'), (1, 'W drogę!'), (2, 'Zakończona')], default=0),
        ),
    ]
