# Generated by Django 4.2.1 on 2023-05-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_travelnotes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelnotes',
            name='date',
        ),
    ]
