# Generated by Django 4.2.1 on 2023-05-20 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_travelnotes_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
