# Generated by Django 4.2.1 on 2023-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_remove_attraction_cost_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='persons',
            field=models.IntegerField(default=1),
        ),
    ]
